// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtZ75j9FvXDqSy-UUG7sCD0cHcEFldoVw',
    appId: '1:909690555879:web:74cc27ec8ef4a29b194142',
    messagingSenderId: '909690555879',
    projectId: 'mit-hostel-application',
    authDomain: 'mit-hostel-application.firebaseapp.com',
    storageBucket: 'mit-hostel-application.appspot.com',
    measurementId: 'G-ZR04KEH7C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO6he4nmD0JVPceCpRpcyTcKPzm0JViG0',
    appId: '1:909690555879:android:e430b21b88da72cc194142',
    messagingSenderId: '909690555879',
    projectId: 'mit-hostel-application',
    storageBucket: 'mit-hostel-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLUGyc7rNCgcV3ODh5RaxNSvxJ_n8JvgY',
    appId: '1:909690555879:ios:ab5bcf55a3ef026c194142',
    messagingSenderId: '909690555879',
    projectId: 'mit-hostel-application',
    storageBucket: 'mit-hostel-application.appspot.com',
    iosBundleId: 'com.example.auberge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtZ75j9FvXDqSy-UUG7sCD0cHcEFldoVw',
    appId: '1:909690555879:web:6d6d1e0b455ca31b194142',
    messagingSenderId: '909690555879',
    projectId: 'mit-hostel-application',
    authDomain: 'mit-hostel-application.firebaseapp.com',
    storageBucket: 'mit-hostel-application.appspot.com',
    measurementId: 'G-1KBBMEMVEG',
  );
}
